### ISSUE TITLE
Add repo to list of cities using MDS

### ISSUE THREAD

**Issue by hunterowens** [stadtulm/mds-zonen#1]
Hi! 

@hunterowens here, from LA City. 

Glad to see MDS spreading far past LA! I'd love for y'all to add this repo to the [list of cities using MDS](https://github.com/cityOfLosAngeles/mobility-data-specification#cities-using-mds). 

It also sounds like y'all are trying to implement pedestrian zones and are having trouble... is there anything we could maybe change in the main spec to make it easier to do.

**Comment by stkdiretto** [comment]
Hey, nice hearing from you! This is just a first quick-and-dirty approach; we plan on defining a process that allows for spec-compatible zones with all the bells and whistles – I am not sure whether this already passes the bar for inclusion in the official list; we are also still evaluating how to receive MDS statistical data in a proper manner.

As for pedestrian zones: We are still discussing internally whether and how to actually implement this. As of now, automated speed throttling is not legal in Germany anyways, so this takes a back bench place as opposed to automating all the other stuff. Any advice on how this works out in other places would be appreciated; we've received mixed signals so far.

**Comment by Sim-Sam** [comment]
@hunterowens thanks, I added Ulm and created a pull request
